### ISSUE TITLE
Running "example_advection.py"

### ISSUE THREAD

**Issue by masumis** [pymgrit/pymgrit#7]
@sfriedhoff @JensHahne @jbschroder

When I run "example_advection.py" in pymgrit/examples, I receive an error message below

TypeError: Can't instantiate abstract class VectorAdvection1D with abstract methods __mul__

Thank you,
Masumi

**Comment by JensHahne** [comment]
Hi Masumi,

this sounds as if your advection vector class misses the __mul__ function, which is required since PyMGRIT version 1.0.5. See the latest version of the advection vector class in line 53. (https://github.com/pymgrit/pymgrit/blob/master/src/pymgrit/advection/advection_1d.py). 

This should solve the problem. Let me know if it does not

Regards,
Jens

**Comment by jbschroder** [comment]
Hi All,

Masumi:  It sounds like maybe you need the most recent version of PyMGRIT
from the master branch.  Are you using that?

- Jacob

**Comment by masumis** [comment]
@JensHahne 

Dear Dr. Hahne,

Thank you for your reply. I think I am using the most recent version of PyMGRIT. I include the first few lines of "git log" below:

commit 910f69e7ee7d71c6940c972c9a9e5d0827c4f6f0 (HEAD -> master, tag: 1.0.5, origin/master, origin/HEAD)
Author: Jens Hahne <jehahne@uni-wuppertal.de>
Date:   Mon Oct 19 10:42:55 2020 +0200
new version number

Thank you,
Masumi

**Comment by JensHahne** [comment]
Hi Masumi,

this should be the latest version. Maybe your installed version is an older version? Please try "pip show pymgrit". If the version is < 1.0.5 you can update the version using "pip install pymgrit --upgrade" or "pip install ."  in the PyMGRIT folder.

-Jens

**Comment by masumis** [comment]
Dear Dr Hahne,

I can run the advection example without any error now. Thank you very much for your help.

Masumi

**Comment by JensHahne** [comment]
Perfect :+1: 

And I am a PhD student, so please just call me Jens :)
