### ISSUE TITLE
[question] How to run induction machine example

### ISSUE THREAD

**Issue by nickvazz** [pymgrit/pymgrit#9]
Hello! I came across your paper and this repo recently and wanted to give it a spin. How would I go about running 
`https://github.com/pymgrit/pymgrit/blob/master/src/pymgrit/induction_machine/induction_machine.py`?

Thank you!

**Comment by JensHahne** [comment]
Hello! Thank you for your interest in PyMGRIT. The first step is to get the software GetDP (https://getdp.info/).

Then you can define the appropriate application class, e.g.

problem = InductionMachine(nonlinear=False, pwm=False, grid='im_3kW_4k', t_start=0, t_stop=0.00002, nt=11,
                               path_getdp='path/to/getdp',
                               path_im3kw='path/to/im_3kw')
                               
Here you need to specify the path to getdp and the path to the model. The model is located here: https://github.com/pymgrit/pymgrit/tree/master/src/pymgrit/induction_machine/im_3kW

After that, you should be able to run the application in the usual way.

Examples can be found here:
https://github.com/pymgrit/pymgrit/blob/master/examples/induction_machine/induction_machine.py
https://github.com/pymgrit/pymgrit/blob/master/examples/at_mgrit/runme_machine.py

In both examples, certain settings for the MGRIT algorithm have been implemented, as described in the corresponding papers. However, these can also be omitted at the beginning.

Let me know if you have any further questions or encounter any problems.
